In [13]:
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Wisconsin')
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor


from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay

In [14]:
bcancer = pd.read_csv('BreastCancer.csv',index_col=0)
bcancer

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,Malignant
1371026,5,10,10,10,4,10,5,6,3,Malignant
1371920,5,1,1,1,2,1,3,2,1,Benign
8233704,4,1,1,1,1,1,2,1,1,Benign
13454352,1,1,3,1,2,1,2,1,1,Benign

In [15]:
X,y = bcancer.drop('Class', axis = 1) , bcancer['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

In [19]:
m_feat = [2,3,4,5]
n_samples = [25,50,100]
scores = []
for m in m_feat:
    for n in n_samples:
        rf = RandomForestClassifier(max_features=m, n_estimators=n,random_state=26)

        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_test)
        scores.append([m, n , f1_score(y_test, y_pred, average='macro')])

df_scores = pd.DataFrame(scores, columns=['Features','n','f1_score'])
df_scores.sort_values(by='f1_score',ascending=False)

    Features    n  f1_score
0          2   25  0.963595
1          2   50  0.963595
2          2  100  0.963595
4          3   50  0.963595
11         5  100  0.963595
5          3  100  0.963595
7          4   50  0.963595
8          4  100  0.963595
10         5   50  0.963595
3          3   25  0.958267
6          4   25  0.953470
9          5   25  0.948148

In [22]:
m_feat = [2,3,4,5]
n_samples = [25,50,100]
scores = []
for m in m_feat:
    for n in n_samples:
        rf = RandomForestClassifier(max_features=m, n_estimators=n,random_state=26)

        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_test)
        scores.append([m, n , precision_score(y_test, y_pred, average='macro')])

df_scores = pd.DataFrame(scores, columns=['Features','n','precision_score'])
df_scores.sort_values(by='precision_score',ascending=False)

    Features    n  precision_score
0          2   25         0.957280
1          2   50         0.957280
2          2  100         0.957280
4          3   50         0.957280
11         5  100         0.957280
5          3  100         0.957280
7          4   50         0.957280
8          4  100         0.957280
10         5   50         0.957280
3          3   25         0.953064
6          4   25         0.945550
9          5   25         0.941142

In [23]:
m_feat = [2,3,4,5]
n_samples = [25,50,100]
scores = []
for m in m_feat:
    for n in n_samples:
        rf = RandomForestClassifier(max_features=m, n_estimators=n,random_state=26)

        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_test)
        scores.append([m, n , recall_score(y_test, y_pred, average='macro')])

df_scores = pd.DataFrame(scores, columns=['Features','n','precision_score'])
df_scores.sort_values(by='precision_score',ascending=False)

    Features    n  precision_score
0          2   25         0.971316
1          2   50         0.971316
2          2  100         0.971316
4          3   50         0.971316
11         5  100         0.971316
5          3  100         0.971316
7          4   50         0.971316
8          4  100         0.971316
10         5   50         0.971316
3          3   25         0.964372
6          4   25         0.964070
9          5   25         0.957126

In [25]:
rf = RandomForestClassifier(max_features=m, n_estimators=n,random_state=26)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      Benign       0.99      0.96      0.97       138
   Malignant       0.92      0.99      0.95        72

    accuracy                           0.97       210
   macro avg       0.96      0.97      0.96       210
weighted avg       0.97      0.97      0.97       210

In [38]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')

vehicle = pd.read_csv('Vehicle.csv')
vehicle

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,saab
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van

In [42]:
X,y = vehicle.drop('Class', axis = 1) , vehicle['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

In [43]:
rf = RandomForestClassifier(random_state=26)

In [44]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         bus       0.92      1.00      0.96        65
        opel       0.60      0.56      0.58        64
        saab       0.60      0.54      0.57        65
         van       0.86      0.93      0.90        60

    accuracy                           0.76       254
   macro avg       0.75      0.76      0.75       254
weighted avg       0.74      0.76      0.75       254

In [45]:
# see for naive predictions theory complete

In [ ]:
naive model acc == our model acc         model no use
naive model acc <  our model acc            model is so good