In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    ridge_regression,
)
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

# Set working directory (using a raw string to avoid escape character issues with backslashes)
os.chdir(
    r"E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets"
)

In [2]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [6]:
X, y = housing.drop('price', axis=1), housing['price']
X_train , X_test , y_train, y_test = train_test_split(X,y,random_state = 26 , test_size = 0.3)

ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')

ct = make_column_transformer(
                            (ohc, make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)
ct = ct.set_output(transform = 'pandas')
x_ohe = ct.fit_transform(X_train)
x_ohe

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,bedrooms,bathrms,stories,garagepl
40,1.0,0.0,1.0,0.0,0.0,0.0,3745,3,1,2,0
197,0.0,0.0,0.0,1.0,0.0,0.0,4350,3,1,2,1
48,0.0,0.0,0.0,0.0,0.0,0.0,4960,4,1,3,0
67,1.0,0.0,1.0,0.0,1.0,0.0,6000,2,1,1,1
26,1.0,0.0,0.0,0.0,0.0,0.0,3800,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
160,1.0,0.0,0.0,0.0,1.0,0.0,3162,3,1,2,1
77,1.0,0.0,1.0,0.0,1.0,0.0,3180,4,1,2,0
102,1.0,0.0,1.0,1.0,0.0,0.0,4320,3,1,2,2
432,1.0,0.0,0.0,0.0,0.0,1.0,6040,3,1,1,2
318,1.0,1.0,0.0,0.0,0.0,0.0,5828,4,1,4,0

In [9]:
lr = LinearRegression()
lr.fit(x_ohe, y_train)

LinearRegression()

In [16]:
X_test_transf = ct.transform(X_test)

y_pred = lr.predict(X_test_transf)
r2score = r2_score(y_test,y_pred)
r2score

0.6791781818067955