In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error ,mean_squared_error,r2_score   # use tab to get auto suggestion 
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [8]:
df = pd.read_csv('Exp_salaries.csv')
df

,Salary,Years_Previous_Experience,Years Employed,Years_Education,Gender,Department,Number_Supervised
0,32782,1,0,7,Male,A,0
1,32920,3,15,9,Female,A,4
2,29548,6,5,1,Male,A,0
3,39828,6,18,5,Female,A,5
4,31528,11,3,3,Male,A,6
5,38985,7,18,9,Male,A,5
6,41889,16,22,7,Male,A,7
7,38791,4,21,5,Male,A,9
8,28985,1,0,4,Female,A,4
9,24749,2,6,0,Female,A,1
10,35467,6,3,6,Female,B,3
11,35468,5,9,4,Female,B,5
12,29876,0,2,3,Female,B,5
13,43674,9,6,4,Male,B,2
14,36431,4,9,4,Female,B,2
15,26578,6,0,2,Female,B,2
16,36571,1,6,4,Male,B,2
17,56326,3,12,8,Male,B,6
18,23654,0,0,0,Female,C,2
19,36578,4,4,8,Male,C,8
20,37548,9,19,4,Male,C,6
21,53234,0,25,6,Male,C,3
22,54679,3,20,6,Female,C,4
23,47536,5,15,6,Male,C,4
24,31425,6,7,5,Female,C,6
25,65487,0,27,12,Female,D,44
26,46184,3,20,4,Male,D,1
27,54899,5,12,8,Female,D,0
28,34869,5,7,4,Female,D,1
29,35487,2,8,2,Female,D,2
30,26548,1,5,0,Male,D,2
31,34231,2,6,6,Male,D,3
32,39331,3,9,6,Female,D,1
33,36512,6,6,4,Female,D,2
34,68425,2,25,12,Male,D,1
35,36487,5,6,2,Male,D,3
36,34632,4,5,4,Male,D,0
37,46211,5,14,6,Female,D,5
38,51698,6,18,6,Male,D,1
39,69246,3,22,10,Male,D,45
40,48695,19,6,8,Male,D,40
41,34987,6,9,2,Female,D,3
42,35631,4,6,4,Male,D,2
43,39743,6,9,5,Female,D,1
44,41255,4,9,6,Male,D,4
45,26452,3,1,2,Female,D,0

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import ridge_regression, Ridge
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error ,mean_squared_error,r2_score   # use tab to get auto suggestion
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
from sklearn.linear_model import ElasticNet 

df = pd.read_csv('Housing.csv')
df

x = df.drop('price', axis=1)
y = df['price']

encoder = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')

num_cols = list(x.columns[x.dtypes == int])
str_cols = list(x.columns[x.dtypes != int])

X_num = X[num_cols]
X_str = X[str_cols]

X_ohe = encoder.fit_transform(X_str)
X_enc = pd.concat([X_ohe,X_num], axis = 1)

X_enc
X_train , X_test, y_train, y_test = train_test_split(X_enc, y , test_size = 0.3, random_state = 26)

ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)

root_mean_squared_error(y_test, y_pred)

ridge.coef_

ridge = Ridge(alpha=0.5)
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
ridge.coef_

ridge.intercept_


 

alphas = [0.1,0.25,0.7,1,1.5,2,5,10,50]
scores =[]


for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, root_mean_squared_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score')

alphas = [0.1,0.25,0.7,1,1.5,2,5,10,50]
ratios = [0.1,0.25,0.5,0.75,1]
scores = []


for a in alphas:
    for r in ratios:
        el = ElasticNet(alpha=a,l1_ratio=r)
        el.fit(X_train,y_train)
        y_pred = el.predict(X_test)
        scores.append([a,r,root_mean_squared_error(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1','score'])        
df_scores.sort_values('score')

    alpha    l1         score
4    0.10  1.00  15052.992867
9    0.25  1.00  15053.119181
14   0.70  1.00  15053.498743
19   1.00  1.00  15053.752302
24   1.50  1.00  15054.175801
29   2.00  1.00  15054.600456
34   5.00  1.00  15057.172338
39  10.00  1.00  15061.550216
44  50.00  1.00  15100.671758
3    0.10  0.75  15249.325211
2    0.10  0.50  15458.917234
8    0.25  0.75  15562.725734
1    0.10  0.25  15664.738951
0    0.10  0.10  15785.242884
7    0.25  0.50  16056.307015
13   0.70  0.75  16417.126036
6    0.25  0.25  16501.667171
5    0.25  0.10  16745.903794
18   1.00  0.75  16900.819224
12   0.70  0.50  17453.266239
23   1.50  0.75  17578.598864
17   1.00  0.50  18131.957965
28   2.00  0.75  18133.111257
11   0.70  0.25  18230.633016
10   0.70  0.10  18611.180207
16   1.00  0.25  18987.523823
22   1.50  0.50  18988.027259
15   1.00  0.10  19388.155512
27   2.00  0.50  19621.753057
21   1.50  0.25  19880.673371
33   5.00  0.75  20113.491211
20   1.50  0.10  20276.866746
26   2.00  0.25  20501.262620
25   2.00  0.10  20876.723773
32   5.00  0.50  21503.015913
38  10.00  0.75  21505.602847
31   5.00  0.25  22159.542379
30   5.00  0.10  22410.141872
37  10.00  0.50  22543.914752
36  10.00  0.25  22971.348708
35  10.00  0.10  23125.226654
43  50.00  0.75  23356.709961
42  50.00  0.50  23664.645942
41  50.00  0.25  23772.617295
40  50.00  0.10  23809.231245