In [5]:
# !pip install mlxtend

In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules



import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

import warnings
warnings.filterwarnings("ignore")

In [4]:
'''
Binary Format: Association rule mining only cares about whether an item was present (True) or absent (False), not how many units were bought.

Algorithm Compatibility: The function relies on boolean matrix operations to quickly calculate support and count itemsets.
'''

'\nBinary Format: Association rule mining only cares about whether an item was present (True) or absent (False), not how many units were bought.\n\nAlgorithm Compatibility: The function relies on boolean matrix operations to quickly calculate support and count itemsets.\n'

In [5]:
fp_df = pd.read_csv('Faceplate.csv',index_col=0)
fp_df = fp_df.astype(bool)
fp_df

               Red  White   Blue  Orange  Green  Yellow
Transaction
1             True   True  False   False   True   False
2            False   True  False    True  False   False
3            False   True   True   False  False   False
4             True   True  False    True  False   False
5             True  False   True   False  False   False
6            False   True   True   False  False   False
7             True  False   True   False  False   False
8             True   True   True   False   True   False
9             True   True   True   False  False   False
10           False  False  False   False  False    True

In [16]:
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
'''
This means the algorithm only keeps itemsets (like individual items or combinations)
that appear in at least 20% of the total transactions in your dataset.
'''
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (Red, White)
6       0.4          (Red, Blue)
7       0.2         (Red, Green)
8       0.4        (White, Blue)
9       0.2      (White, Orange)
10      0.2       (Green, White)
11      0.2   (Red, White, Blue)
12      0.2  (Red, Green, White)

In [20]:
rules = association_rules(itemsets , metric='confidence' , min_threshold=0.5)
rules.sort_values(by=['confidence','lift','support'], ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
15,(Green),"(Red, White)",0.2,0.4,0.2,1.000000,2.500000,1.0,0.12,inf,0.750000,0.500000,1.000000,0.750000
4,(Green),(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500000,0.333333,1.000000,0.666667
14,"(Green, White)",(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500000,0.333333,1.000000,0.666667
7,(Orange),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
8,(Green),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
12,"(Red, Green)",(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375000,0.285714,1.000000,0.642857
2,(Red),(Blue),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.200000,0.250000,0.500000,0.166667,0.666667
3,(Blue),(Red),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.200000,0.250000,0.500000,0.166667,0.666667
0,(Red),(White),0.6,0.7,0.4,0.666667,0.952381,1.0,-0.02,0.900000,-0.111111,0.444444,-0.111111,0.619048
6,(Blue),(White),0.6,0.7,0.4,0.666667,0.952381,1.0,-0.02,0.900000,-0.111111,0.444444,-0.111111,0.619048
1,(White),(Red),0.7,0.6,0.4,0.571429,0.952381,1.0,-0.02,0.933333,-0.142857,0.444444,-0.071429,0.619048
5,(White),(Blue),0.7,0.6,0.4,0.571429,0.952381,1.0,-0.02,0.933333,-0.142857,0.444444,-0.071429,0.619048
13,"(Red, White)",(Green),0.4,0.2,0.2,0.500000,2.500000,1.0,0.12,1.600000,1.000000,0.500000,0.375000,0.750000
9,"(Red, White)",(Blue),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
11,"(White, Blue)",(Red),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
10,"(Red, Blue)",(White),0.4,0.7,0.2,0.500000,0.714286,1.0,-0.08,0.600000,-0.400000,0.222222,-0.666667,0.392857

In [19]:
relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
15,(Green),"(Red, White)",0.2,0.4,0.2,1.000000,2.500000,1.0,0.12,inf,0.750,0.500000,1.000000,0.750000
4,(Green),(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500,0.333333,1.000000,0.666667
14,"(Green, White)",(Red),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500,0.333333,1.000000,0.666667
7,(Orange),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375,0.285714,1.000000,0.642857
8,(Green),(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375,0.285714,1.000000,0.642857
12,"(Red, Green)",(White),0.2,0.7,0.2,1.000000,1.428571,1.0,0.06,inf,0.375,0.285714,1.000000,0.642857
2,(Red),(Blue),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250,0.500000,0.166667,0.666667
3,(Blue),(Red),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250,0.500000,0.166667,0.666667
13,"(Red, White)",(Green),0.4,0.2,0.2,0.500000,2.500000,1.0,0.12,1.6,1.000,0.500000,0.375000,0.750000