In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules



import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

import warnings
warnings.filterwarnings("ignore")

In [7]:
cs_df = pd.read_csv('Coursetopics.csv')
cs_df = cs_df.astype(bool)
cs_df

     Intro  DataMining  Survey  Cat Data  Regression  Forecast    DOE     SW
0     True        True   False     False       False     False  False  False
1    False       False    True     False       False     False  False  False
2    False        True   False      True        True     False  False   True
3     True       False   False     False       False     False  False  False
4     True        True   False     False       False     False  False  False
..     ...         ...     ...       ...         ...       ...    ...    ...
360  False       False   False      True       False     False  False  False
361  False        True   False      True       False     False  False   True
362  False       False   False     False       False     False  False   True
363  False       False   False      True       False     False  False  False
364  False       False   False     False        True     False  False  False

[365 rows x 8 columns]

In [22]:
itemsets = apriori(cs_df, min_support=0.07, use_colnames=True)
itemsets

     support             itemsets
0   0.394521              (Intro)
1   0.178082         (DataMining)
2   0.186301             (Survey)
3   0.208219           (Cat Data)
4   0.208219         (Regression)
5   0.139726           (Forecast)
6   0.172603                (DOE)
7   0.221918                 (SW)
8   0.071233    (Cat Data, Intro)
9   0.071233  (Regression, Intro)
10  0.095890          (SW, Intro)

In [23]:
rules = association_rules(itemsets , metric='confidence' , min_threshold=0.5)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
rules.sort_values(by=['confidence','lift','support'], ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [24]:
relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [25]:
from ipywidgets import interact
import ipywidgets as widgets

In [26]:
def gen_rules(min_support , minconfidence):
    itemsets = apriori(cs_df, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets , metric='confidence' , min_threshold=minconfidence)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
    relv_rules= rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

In [29]:
interact(
    gen_rules , 
    min_support = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.4 , step = 0.01 , description = 'Min Support:'
    ),
    minconfidence = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.5 , step = 0.01, description = 'Min Confidence:'
    )
)

interactive(children=(FloatSlider(value=0.2, description='Min Support:', max=0.4, min=0.01, step=0.01), FloatS…