In [1]:
import pandas as pd

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder


import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')
import warnings
warnings.filterwarnings("ignore")

In [2]:
# we cant read this groceries.csv file directly it contains comma separed items with transaction on new line

In [3]:

groceries = []
with open('Groceries.csv',"r") as f:groceries = f.read()
groceries = groceries.split("\n")

groceries_list = []
for i in groceries:
    groceries_list.append(i.split(","))
# groceries
# groceries_list

In [4]:
te = TransactionEncoder()
te_ary = te.fit(groceries_list).transform(groceries_list)
fp_df = pd.DataFrame(te_ary , columns=te.columns_)
fp_df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [5]:
itemsets = apriori(fp_df, min_support=0.07, use_colnames=True)
itemsets

     support                        itemsets
0   0.080529                  (bottled beer)
1   0.110524                 (bottled water)
2   0.077682                   (canned beer)
3   0.082766                  (citrus fruit)
4   0.072293         (fruit/vegetable juice)
5   0.079817                    (newspapers)
6   0.193493              (other vegetables)
7   0.088968                        (pastry)
8   0.075648                     (pip fruit)
9   0.183935                    (rolls/buns)
10  0.108998               (root vegetables)
11  0.093950                       (sausage)
12  0.098526                 (shopping bags)
13  0.174377                          (soda)
14  0.104931                (tropical fruit)
15  0.071683            (whipped/sour cream)
16  0.255516                    (whole milk)
17  0.139502                        (yogurt)
18  0.074835  (whole milk, other vegetables)

In [6]:
rules = association_rules(itemsets , metric='confidence' , min_threshold=0.2)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
rules.sort_values(by=['confidence','lift','support'], ascending=False)

          antecedents         consequents   support  confidence      lift
1  (other vegetables)        (whole milk)  0.074835    0.386758  1.513634
0        (whole milk)  (other vegetables)  0.074835    0.292877  1.513634

In [7]:
relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

          antecedents         consequents   support  confidence      lift
1  (other vegetables)        (whole milk)  0.074835    0.386758  1.513634
0        (whole milk)  (other vegetables)  0.074835    0.292877  1.513634

In [8]:
from ipywidgets import interact
import ipywidgets as widgets

In [9]:
def gen_rules(min_support , minconfidence):
    itemsets = apriori(fp_df, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets , metric='confidence' , min_threshold=minconfidence)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
    relv_rules= rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

In [10]:
interact(
    gen_rules , 
    min_support = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.4 , step = 0.01 , description = 'Min Support:'
    ),
    minconfidence = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.5 , step = 0.01, description = 'Min Confidence:'
    )
)

interactive(children=(FloatSlider(value=0.2, description='Min Support:', max=0.4, min=0.01, step=0.01), FloatS…