In [5]:
# !pip install mlxtend

In [8]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules



import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

import warnings
warnings.filterwarnings("ignore")

In [13]:
fp_df = pd.read_csv('Faceplate.csv',index_col=0)
fp_df = fp_df.astype(bool)
fp_df

               Red  White   Blue  Orange  Green  Yellow
Transaction
1             True   True  False   False   True   False
2            False   True  False    True  False   False
3            False   True   True   False  False   False
4             True   True  False    True  False   False
5             True  False   True   False  False   False
6            False   True   True   False  False   False
7             True  False   True   False  False   False
8             True   True   True   False   True   False
9             True   True   True   False  False   False
10           False  False  False   False  False    True

In [15]:
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Blue, Red)
7       0.2         (Red, Green)
8       0.4        (White, Blue)
9       0.2      (White, Orange)
10      0.2       (White, Green)
11      0.2   (White, Blue, Red)
12      0.2  (White, Red, Green)