In [3]:
import pandas as pd
import numpy as np
import os
from sklearn.ensemble import IsolationForest
os.chdir('E:\PGCP-AI\PML\Datasets')

In [5]:
df = pd.read_csv('milk.csv', index_col = 0)
df

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [16]:
df = pd.read_csv('nutrient.csv', index_col = 0)
df

                     energy  protein  fat  calcium  iron
Food_Item
BEEF BRAISED            340       20   28        9   2.6
HAMBURGER               245       21   17        9   2.7
BEEF ROAST              420       15   39        7   2.0
BEEF STEAK              375       19   32        9   2.6
BEEF CANNED             180       22   10       17   3.7
CHICKEN BROILED         115       20    3        8   1.4
CHICKEN CANNED          170       25    7       12   1.5
BEEF HEART              160       26    5       14   5.9
LAMB LEG ROAST          265       20   20        9   2.6
LAMB SHOULDER ROAST     300       18   25        9   2.3
SMOKED HAM              340       20   28        9   2.5
PORK ROAST              340       19   29        9   2.5
PORK SIMMERED           355       19   30        9   2.4
BEEF TONGUE             205       18   14        7   2.5
VEAL CUTLET             185       23    9        9   2.7
BLUEFISH BAKED          135       22    4       25   0.6
CLAMS RAW                70       11    1       82   6.0
CLAMS CANNED             45        7    1       74   5.4
CRABMEAT CANNED          90       14    2       38   0.8
HADDOCK FRIED           135       16    5       15   0.5
MACKEREL BROILED        200       19   13        5   1.0
MACKEREL CANNED         155       16    9      157   1.8
PERCH FRIED             195       16   11       14   1.3
SALMON CANNED           120       17    5      159   0.7
SARDINES CANNED         180       22    9      367   2.5
TUNA CANNED             170       25    7        7   1.2
SHRIMP CANNED           110       23    1       98   2.6

In [17]:


clf = IsolationForest(contamination = 0.05 , random_state=26)
clf.fit(df)

predictions = clf.predict(df)
print(predictions)
print('% age of outliers = '+str((predictions<0).mean()*100)+ ' %')
abn_ind = np.where(predictions < 0)
 
abn_ind

[ 1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1
  1  1  1]
% age of outliers = 7.4074074074074066 %

(array([ 2, 17]),)

In [18]:
df.index[abn_ind]

Index(['BEEF ROAST', 'CLAMS CANNED'], dtype='object', name='Food_Item')