In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis , QuadraticDiscriminantAnalysis
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [3]:
iris = pd.read_csv('iris.csv')
iris

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:

X , y = iris.drop('Species', axis=1), iris['Species']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26 ,stratify=y)

In [5]:
scaler = StandardScaler()

ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)

    pipe = Pipeline([('SCL', scaler),('KNN', knn)])
    pipe.fit(X_train , y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
0    1  0.955556
4    5  0.955556
12  13  0.955556
9   10  0.933333
13  14  0.933333
10  11  0.933333
5    6  0.933333
14  15  0.933333
6    7  0.911111
2    3  0.911111
3    4  0.911111
7    8  0.911111
8    9  0.911111
11  12  0.911111
1    2  0.844444