In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import BernoulliNB,GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer 
from sklearn.compose import make_column_transformer,make_column_selector
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\student_performance')

In [39]:
studper = pd.read_csv('student_dataset_10000_rows.csv')
studper

      study_hours  attendance  sleep_hours  ...  previous_score  exam_score  placement_status
0               7          56            8  ...              62      100.00            Placed
1               4          69            5  ...              56      100.00            Placed
2              11          60            7  ...              45      100.00            Placed
3               8          99            9  ...              55       90.17            Placed
4               5          52            8  ...              40       78.82            Placed
...           ...         ...          ...  ...             ...         ...               ...
9995            2          58            9  ...              88       69.31        Not Placed
9996            7          98            6  ...              87      100.00            Placed
9997           10          44            8  ...              37       95.94            Placed
9998           10          75            7  ...              52       88.61            Placed
9999            2          70            6  ...              52       78.96            Placed

[10000 rows x 8 columns]

In [35]:
X,y = studper.drop('placement_status', axis = 1) , studper['placement_status']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26,stratify=y)

In [45]:
nb = GaussianNB()
 
nb.fit(X_train, y_train)
 
y_pred = nb.predict(X_test) # gen outcome with highest prob
accuracy_score(y_test, y_pred)

0.961

In [46]:
nbs = range(1,15)
res =[] 
for i in nbs:
    
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(X_train, y_train)
 
    y_pred = knn.predict(X_test) # gen outcome with highest prob
    res.append([i , accuracy_score(y_test, y_pred)])

rs = pd.DataFrame(res , columns=['K', 'accuracy'])
rs.sort_values(by='accuracy', ascending = False)

     K  accuracy
8    9  0.988667
9   10  0.988667
13  14  0.988667
12  13  0.988667
10  11  0.988000
4    5  0.986333
11  12  0.986333
7    8  0.985333
6    7  0.984000
2    3  0.983667
5    6  0.983667
3    4  0.983667
0    1  0.977667
1    2  0.974000

### After scaling check the accuracy

In [48]:
scaler = StandardScaler().set_output(transform = 'pandas')
scaled_x_train  = scaler.fit_transform(X_train)
scaled_x_test  = scaler.transform(X_test)


nb = GaussianNB()
 
nb.fit(scaled_x_train, y_train)
 
y_pred = nb.predict(scaled_x_test) # gen outcome with highest prob
accuracy_score(y_test, y_pred)

0.961

In [49]:
nbs = range(1,15)
res =[] 
for i in nbs:
    
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(scaled_x_train, y_train)
 
    y_pred = knn.predict(scaled_x_test) # gen outcome with highest prob
    res.append([i , accuracy_score(y_test, y_pred)])

rs = pd.DataFrame(res , columns=['K', 'accuracy'])
rs.sort_values(by='accuracy', ascending = False)

     K  accuracy
12  13  0.972333
13  14  0.971667
7    8  0.971000
11  12  0.969667
8    9  0.969333
6    7  0.968667
10  11  0.968333
9   10  0.968000
5    6  0.967333
4    5  0.965333
2    3  0.962000
3    4  0.960000
0    1  0.952000
1    2  0.951000