In [63]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis , QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer , make_column_selector,make_column_transformer
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\student_performance')

# Logistic regression On Student Dataset

In [48]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\student_performance')

In [49]:
df = pd.read_csv('student_dataset_10000_rows.csv')
df
X , y = df.drop('placement_status', axis=1), df['placement_status']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26 ,stratify=y)

In [50]:
lr  = LogisticRegression()
lr.fit(X_train, y_train)
y_pred  = lr.predict(X_test)
accuracy_score(y_test , y_pred)

0.9993333333333333

# Logistic regression On Kyposis

In [51]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Kyphosis')

In [52]:
df = pd.read_csv('Kyphosis.csv')
df
X , y = df.drop('Kyphosis', axis=1), df['Kyphosis']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26 ,stratify=y)

In [53]:
lr  = LogisticRegression()
lr.fit(X_train, y_train)
y_pred  = lr.predict(X_test)
accuracy_score(y_test , y_pred)

0.88

In [54]:
import sklearn
sklearn.__version__

'1.9.0'

# Logistic regression On HR CSV

In [55]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\human-resources-analytics')

In [56]:
hr = pd.read_csv('HR_comma_sep.csv')
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [75]:
X , y = hr.drop('left', axis=1), hr['left']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26 ,stratify=y)

In [76]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
scaler = StandardScaler().set_output(transform='pandas')


col_transformer = make_column_transformer(
                            (ohe,           make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False).set_output(transform='pandas')

In [78]:
solvers=['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']

scores  =[]

for s in solvers:
    lr  = LogisticRegression(solver=s)
    pipe = Pipeline([('CT',col_transformer),('LR', lr)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s , accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores , columns=['solver','score'])
df_scores

E:\Installed_Applications\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Installed_Applications\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
E:\Installed_Applications\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

            solver     score
0            lbfgs  0.800845
1        liblinear  0.792843
2        newton-cg  0.793065
3  newton-cholesky  0.793065
4              sag  0.753056
5             saga  0.760613

In [79]:
solvers=[ 'liblinear' ,'saga']

scores  =[]

for s in solvers:
    lr  = LogisticRegression(solver=s)
    pipe = Pipeline([('CT',col_transformer),('LR', lr)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s , accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores , columns=['solver','score'])
df_scores

E:\Installed_Applications\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

      solver     score
0  liblinear  0.792843
1       saga  0.760613