In [26]:
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Kyphosis')
import pandas as pd
import numpy as np 

from tqdm import tqdm

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay , roc_curve, RocCurveDisplay, roc_auc_score

In [27]:
df = pd.read_csv('Kyphosis.csv')
df

   Kyphosis  Age  Number  Start
0    absent   71       3      5
1    absent  158       3     14
2   present  128       4      5
3    absent    2       5      1
4    absent    1       4     15
..      ...  ...     ...    ...
76  present  157       3     13
77   absent   26       7     13
78   absent  120       2     13
79  present   42       7      6
80   absent   36       4     13

[81 rows x 4 columns]

In [28]:
X,y = df.drop('Kyphosis', axis = 1) , df['Kyphosis']

le = LabelEncoder()
le_y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X,le_y, test_size = 0.3, random_state=26,stratify=le_y)

In [29]:
gbm = GradientBoostingClassifier(random_state = 26)
gbm.fit(X_train, y_train)
y_pred = gbm.predict(X_test)
roc_auc_score(y_test, y_pred)

0.45

In [31]:
gbm = GradientBoostingClassifier(random_state = 26)
gbm.fit(X_train, y_train)
y_pred_proba = gbm.predict_proba(X_test)
roc_auc_score(y_test, y_pred_proba[:,1])

0.45999999999999996

In [33]:
y_pred_proba

array([[9.90198405e-01, 9.80159509e-03],
       [9.94870218e-01, 5.12978206e-03],
       [9.99634601e-01, 3.65399231e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.69305076e-01, 3.06949244e-02],
       [9.99747678e-01, 2.52322362e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.98099406e-01, 1.90059361e-03],
       [9.99430282e-01, 5.69717995e-04],
       [4.74818489e-01, 5.25181511e-01],
       [9.95574069e-01, 4.42593120e-03],
       [9.98584554e-01, 1.41544561e-03],
       [9.99251679e-01, 7.48321086e-04],
       [9.91940841e-01, 8.05915922e-03],
       [9.99609395e-01, 3.90604918e-04],
       [9.76052239e-01, 2.39477614e-02],
       [9.99024693e-01, 9.75307300e-04],
       [1.67192456e-01, 8.32807544e-01],
       [9.99937391e-01, 6.26093811e-05],
       [9.92054516e-01, 7.94548413e-03],
       [9.97043144e-01, 2.95685582e-03],
       [9.99430282e-01, 5.69717995e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.99769454e-01, 2.30546324e-04],
       [9.90265091e-01, 9.73490861e-03]])

In [36]:

learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = GradientBoostingClassifier(random_state = 26, learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred_proba = gbm.predict_proba(X_test) 

            scores.append([l, d, n ,roc_auc_score(y_test, y_pred_proba[:,1])])
            
df_scores = pd.DataFrame(scores , columns=['learning_rate','max_depth','n_estimator','roc_auc_score'])
df_scores.sort_values(by='roc_auc_score' , ascending=False)

100%|██████████| 10/10 [00:08<00:00,  1.20it/s]

    learning_rate  max_depth  n_estimator  roc_auc_score
3        0.010000        2.0           25          0.830
4        0.010000        2.0           50          0.805
5        0.010000        2.0          100          0.785
87       0.702222        2.0           25          0.705
75       0.603333        2.0           25          0.700
..            ...        ...          ...            ...
74       0.603333        NaN          100          0.255
50       0.405556        NaN          100          0.245
49       0.405556        NaN           50          0.245
84       0.702222        NaN           25          0.230
26       0.207778        NaN          100          0.225

[120 rows x 4 columns]