In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:


df = pd.read_csv('marathon_results_2017.csv')
df.head(2)

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
1,1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2

In [14]:
total_males= len(df[df['M/F'] == 'M'])
total_females= len(df[df['M/F'] == 'F'])
print(total_females, total_males)
origininal_row_count = len(df)

11972 14438

In [15]:
sample_males = int(0.1 * total_males)
sample_females = int(0.1 * total_females)
print(f"Sample needs {sample_males} males and {sample_females} females")

male_sample = df[df['M/F'] == 'M'].sample(n=sample_males, random_state=42)
female_sample = df[df['M/F'] == 'F'].sample(n=sample_females, random_state=42)

sample_df = pd.concat([male_sample,female_sample])

sample_df.head()

Sample needs 1443 males and 1197 females

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
5233,5233,1320,"Woltjer, Joseph",29,M,Charlotte,NC,USA,NaN,NaN,...,1:43:41,2:11:16,2:45:01,3:11:59,0:07:44,-,3:22:44,5234,4418,2447
960,960,4836,"Fan, Alexander",31,M,Woodbury,MN,USA,NaN,NaN,...,1:40:59,2:02:10,2:23:50,2:45:44,0:06:42,-,2:55:40,961,908,714
3179,3179,4663,"Forget, Yves",45,M,Winnipeg,MB,CAN,NaN,NaN,...,1:50:26,2:14:05,2:38:21,3:02:00,0:07:20,-,3:12:12,3180,2860,319
7492,7492,2938,"Johnson, Jamie",37,M,Edmonds,WA,USA,NaN,NaN,...,2:02:43,2:26:23,2:50:50,3:20:16,0:08:05,-,3:31:47,7494,5837,2881
3001,3001,1603,"Poluianov, Viacheslav",39,M,Perm,NaN,RUS,NaN,NaN,...,1:51:54,2:15:02,2:38:21,3:01:20,0:07:18,-,3:11:05,3002,2716,1763

In [16]:
print(f"No of rows in original df {len(sample_df)}")
print(f"No of male athelete in sample df {(sample_df['M/F'] =='M').sum() }")
print(f"No of female athelete in sample df {(sample_df['M/F'] =='F').sum()}")

No of rows in original df 2640
No of male athelete in sample df 1443
No of female athelete in sample df 1197

In [29]:
#clustring sampling: cluster  = countries
unique_countries = df['Country'].unique()
num_countries = len(unique_countries)

print(unique_countries ,"\n\n")
print(num_countries)

<ArrowStringArray>
['KEN', 'USA', 'JPN', 'ETH', 'ZIM', 'MEX', 'BRN', 'BRA', 'CAN', 'ITA', 'NED',
 'IRL', 'BDI', 'GBR', 'GER', 'ESP', 'SUI', 'COL', 'NOR', 'POL', 'FRA', 'RUS',
 'POR', 'CRC', 'BEL', 'NZL', 'PER', 'DOM', 'PAN', 'AUS', 'DEN', 'MAS', 'PHI',
 'CHI', 'AUT', 'ARG', 'SIN', 'CHN', 'TWN', 'GUA', 'RSA', 'HKG', 'SLO', 'EST',
 'TUR', 'EGY', 'IND', 'UAE', 'SWE', 'BER', 'KOR', 'CAY', 'FIN', 'LTU', 'GRE',
 'CRO', 'ISL', 'LUX', 'FLK', 'VEN', 'JAM', 'THA', 'HON', 'SRB', 'CZE', 'ISR',
 'MLT', 'HUN', 'ECU', 'KSA', 'ESA', 'MAR', 'ROU', 'LAT', 'UKR', 'SMR', 'BUL',
 'ALG', 'NCA', 'SVK', 'AND', 'BAR', 'INA', 'GRN', 'URU', 'PAR', 'TCA', 'KUW',
 'TRI', 'MGL', 'NGR']
Length: 91, dtype: str


91

In [26]:
# randomly salect half of the countries
np.random.seed(42)
selected_countries = np.random.choice(unique_countries, size=num_countries//2 , replace=False)
print(selected_countries)
print(len(selected_countries))

['RSA' 'POR' 'CRO' 'TRI' 'KEN' 'PER' 'GUA' 'MLT' 'NED' 'TUR' 'PAR' 'ARG'
 'ESA' 'HON' 'BDI' 'ZIM' 'NOR' 'PAN' 'BER' 'CZE' 'ESP' 'HUN' 'ALG' 'DEN'
 'CHI' 'IRL' 'ISR' 'ECU' 'MAS' 'BUL' 'ITA' 'KSA' 'MEX' 'SLO' 'UAE' 'SUI'
 'EGY' 'AUT' 'BRA' 'SVK' 'DOM' 'POL' 'SMR' 'NZL' 'LTU']
45

In [ ]:
# all records of the selected countries
sample_df = df[df['Country'].isin(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )]
sample_df.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
4,4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5
13,13,16,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,NaN,NaN,...,1:19:54,1:36:39,1:53:55,2:10:20,0:05:16,-,2:17:40,14,14,12
14,14,10,"Korir, Wesley",34,M,Kitale,NaN,KEN,NaN,NaN,...,1:17:08,1:34:17,1:51:50,2:09:58,0:05:17,-,2:18:14,15,15,13
17,17,3,"Mutai, Emmanuel",32,M,Lessos,NaN,KEN,NaN,NaN,...,1:16:59,1:33:24,1:51:32,2:10:44,0:05:20,-,2:19:33,18,18,15

In [22]:
origininal_row_count # no of rows in original df

26410

In [24]:
len(sample_df)   # no of rows in sampled df

1555