In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    ridge_regression,
)
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\human-resources-analytics')

In [13]:
df = pd.read_csv('HR_comma_sep.csv')
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [20]:
df = pd.read_csv('HR_comma_sep.csv')
df

X = df.drop('left', axis=1)
y = df['left']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)


ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
ct = make_column_transformer(
                            (ohc,           make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)


ct = ct.set_output(transform = 'pandas')
scaler = StandardScaler().set_output(transform='pandas')
knn = KNeighborsClassifier(n_neighbors=3)


pipe = Pipeline([("ohe_enc",ct),("scal", scaler),('knn', knn)])

pipe.fit(X_train, y_train)


accuracy_score(y_test , pipe.predict(X_test))

0.9482107134918871

In [21]:
ks = range(1,15)
scores = []
for k in ks: 
    pipe = Pipeline([("ohe_enc",ct),("scal", scaler),('knn', knn)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])
    
df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
0    1  0.948211
1    2  0.948211
2    3  0.948211
3    4  0.948211
4    5  0.948211
5    6  0.948211
6    7  0.948211
7    8  0.948211
8    9  0.948211
9   10  0.948211
10  11  0.948211
11  12  0.948211
12  13  0.948211
13  14  0.948211

In [25]:
test_hr_data = pd.read_csv('tst_hr.csv')

test_hr_data['predicted left'] =  pipe.predict(test_hr_data)
test_hr_data

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department,salary,predicted left
0,0.11,0.88,7,272,4,0,0,sales,medium,1
1,0.72,0.87,5,223,5,0,0,sales,low,0
2,0.37,0.52,2,159,3,0,0,sales,low,1
3,0.41,0.50,2,153,3,0,0,sales,low,1
4,0.67,0.61,3,202,2,0,0,technical,medium,0
5,0.76,0.62,3,150,2,1,0,technical,high,0
6,0.19,0.78,5,156,6,0,0,technical,medium,0
7,0.52,0.73,2,233,3,0,0,technical,medium,1
8,0.66,0.59,5,262,2,0,0,technical,medium,0
9,0.95,0.67,3,183,3,0,0,support,medium,0
10,0.95,0.78,4,225,2,0,0,support,medium,0
11,0.57,0.54,5,216,3,0,0,support,medium,0
12,0.48,0.57,5,227,3,0,0,support,medium,0
13,0.95,0.50,4,242,2,0,0,support,medium,0
14,0.70,0.67,4,224,3,0,0,support,medium,0