In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import BernoulliNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Telecom')

In [57]:
telecom = pd.read_csv('Telecom.csv')
telecom

    Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

In [58]:
telecom = pd.read_csv('Telecom.csv')
X, y = telecom.drop('Response', axis = 1), telecom['Response']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
nb = BernoulliNB()

pipe = Pipeline([('OHE', ohc),('NB', nb)])
pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)
accuracy_score(y_test, y_pred)

0.9111111111111111

In [59]:
# Get predicted probabilities for each class on the test set
pipe.predict_proba(X_test)       # predict prob is in all where classification algo

array([[0.94176709, 0.05823291],
       [0.53640416, 0.46359584],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.50267964, 0.49732036],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.94176709, 0.05823291],
       [0.53640416, 0.46359584],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.50267964, 0.49732036],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.94176709, 0.05823291],
       [0.50267964, 0.49732036],
       [0.06743882, 0.93256118],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.50267964, 0.49732036],
       [0.94176709, 0.05823291],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.06743882, 0.93256118],
       [0.94176709, 0.05823291],
       [0.50267964, 0.49732036],
       [0.50267964, 0.49732036],
       [0.06743882, 0.93256118]])

In [60]:
telecom = pd.read_csv('Telecom.csv')
X, y = telecom.drop('Response', axis = 1), telecom['Response']
ohc = OneHotEncoder(sparse_output = False, drop = 'first') 
ohc.fit_transform(X)

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.]])

Example : On Cancer dataset BernoulliNB

In [61]:

import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Cancer')

In [62]:
cancer = pd.read_csv('Cancer.csv',index_col=0)
X, y = cancer.drop('Class', axis = 1), cancer['Class']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

X

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
subjid,,,,,,,,,
1,40-49,premeno,15 to 19,0 to 2,yes,three,right,left_up,no
2,50-59,ge40,15 to 19,0 to 2,no,one,right,central,no
3,50-59,ge40,35 to 39,0 to 2,no,two,left,left_low,no
4,40-49,premeno,35 to 39,0 to 2,yes,three,right,left_low,yes
5,40-49,premeno,30 to 34,3 to 5,yes,two,left,right_up,no
...,...,...,...,...,...,...,...,...,...
282,50-59,ge40,30 to 34,6 to 8,yes,two,left,left_low,no
283,50-59,premeno,25 to 29,3 to 5,yes,two,left,left_low,yes
284,30-39,premeno,30 to 34,6 to 8,yes,two,right,right_up,no
285,50-59,premeno,15 to 19,0 to 2,no,two,right,left_low,no
286,50-59,ge40,40 to 44,0 to 2,no,three,left,right_up,no

In [63]:
cancer.dtypes

age            str
menopause      str
tumor-size     str
inv-nodes      str
node-caps      str
deg-malig      str
breast         str
breast-quad    str
irradiat       str
Class          str
dtype: object

In [64]:
imputer = SimpleImputer(strategy='most_frequent').set_output(transform='pandas')
col_transformer = make_column_transformer(
                            (imputer,           make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False) 

ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
nb = BernoulliNB()

In [65]:

pipe = Pipeline([("COLT",col_transformer),('OHE', ohc),('NB', nb)])
pipe.fit(X_train, y_train)
 
y_pred = pipe.predict(X_test) # gen outcome with highest prob
accuracy_score(y_test, y_pred)

0.7093023255813954