In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    ridge_regression,
)
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures
from sklearn.impute import SimpleImputer

import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [24]:
loan = pd.read_csv('loan.csv',index_col=0)
loan

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
Loan_ID,,,,,,,,,,,,
LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [26]:
loan.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [20]:
imputer = SimpleImputer(strategy='most_frequent').set_output(transform='pandas')
# loan = imputer.fit_transform(loan)

In [32]:
loan = pd.read_csv('loan.csv',index_col=0)
X , y = loan.drop('Loan_Status' , axis = 1), loan['Loan_Status']

imp_cat = SimpleImputer(strategy='most_frequent').set_output(transform='pandas')
imp_num = SimpleImputer().set_output(transform='pandas')

ct_imp = make_column_transformer(
                            (imp_cat,           make_column_selector(dtype_include = object)),
                            (imp_num, make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False) 

ct_imp = ct_imp.set_output(transform = 'pandas')

X_trans = ct_imp.fit_transform(X)
X_trans.isnull().sum().sum()

np.int64(0)

In [35]:
ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
ct_ohe = make_column_transformer(
                            (ohc,           make_column_selector(dtype_include = object)),
                            ("passthrough", make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)

ct_ohe = ct_ohe.set_output(transform='pandas')
X_trans_ohe = ct_ohe.fit_transform(X_trans)
X_trans_ohe

,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
Loan_ID,,,,,,,,,,,,,,
LP001002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5849.0,0.0,146.412162,360.0,1.0
LP001003,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4583.0,1508.0,128.000000,360.0,1.0
LP001005,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3000.0,0.0,66.000000,360.0,1.0
LP001006,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2583.0,2358.0,120.000000,360.0,1.0
LP001008,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6000.0,0.0,141.000000,360.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LP002978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2900.0,0.0,71.000000,360.0,1.0
LP002979,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4106.0,0.0,40.000000,180.0,1.0
LP002983,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,8072.0,240.0,253.000000,360.0,1.0
LP002984,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,7583.0,0.0,187.000000,360.0,1.0
LP002990,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4583.0,0.0,133.000000,360.0,0.0