In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [5]:
df= pd.read_csv('milk.csv', index_col=0)
df

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

# Standard Scaler

In [14]:
df= pd.read_csv('milk.csv', index_col=0)

scaler = StandardScaler().set_output(transform = 'pandas')
scaler.fit(df)  # calc mean and Standard deviation for all cols
print('Column means ', scaler.mean_)
print('Column SD ', scaler.scale_)

Column means  [78.184   6.212  10.308   4.132   0.8632]
Column SD  [12.55893881  3.57875062 10.30549058  1.79481921  0.49462487]

In [15]:
scaler.transform(df)

               water   protein       fat   lactose       ash
Animal
HORSE       0.948806 -1.009291 -0.903208  1.542217 -1.037554
ORANGUTAN   0.821407 -1.344603 -0.660619  1.040773 -1.259945
MONKEY      0.813445 -1.121062 -0.738247  1.263637 -1.381249
DONKEY      0.964731 -1.260775 -0.864394  1.152205 -0.936467
HIPPO       0.972694 -1.568145 -0.563583  0.149319 -1.542988
CAMEL       0.757707 -0.757806 -0.670322  0.372182 -0.309730
BISON       0.694008 -0.394551 -0.835283  0.873626  0.074400
BUFFALO     0.311810 -0.087181 -0.233662  0.316466 -0.168208
GUINEA PIG  0.295885  0.331959 -0.301587 -0.797852 -0.026687
CAT         0.271998  1.086413 -0.388919  0.149319 -0.228860
FOX         0.271998  0.108418 -0.427733  0.427898  0.135052
LLAMA       0.662158 -0.646036 -0.689729  0.817910 -0.127774
MULE        0.940844 -1.176947 -0.825579  0.762194 -0.794946
PIG         0.367547  0.248131 -0.505362 -0.240693  0.478747
ZEBRA       0.638270 -0.897520 -0.534472  0.650762 -0.329947
SHEEP       0.303847 -0.171009 -0.379215  0.316466  0.094617
DOG        -0.150013  0.862871 -0.078405 -0.630704  0.680920
ELEPHANT   -0.595910 -0.729864  0.707584  0.817910 -0.471468
RABBIT     -0.548135  1.701152  0.270924 -1.243579  2.904828
RAT        -0.452586  0.834928  0.222406 -0.463556  1.085267
DEER       -0.978108  1.170241  0.911359 -0.853568  1.085267
REINDEER   -1.065695  1.254069  0.969580 -0.909284  1.085267
WHALE      -1.065695  1.365840  1.056912 -1.410727  1.691787
SEAL       -2.530787  0.974642  3.075254 -2.302182 -0.026687
DOLPHIN    -2.650224  1.226126  2.386301 -1.800738 -0.673642