In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier , plot_tree, DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression, Lasso, Ridge
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor
from sklearn.ensemble import VotingClassifier,VotingRegressor

from sklearn.metrics import accuracy_score, r2_score
from sklearn.compose import ColumnTransformer , make_column_selector,make_column_transformer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.pipeline import Pipeline
from tqdm import tqdm
from sklearn.ensemble import BaggingClassifier , BaggingRegressor


from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
import os 
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Wisconsin')

In [41]:
bcancer = pd.read_csv('BreastCancer.csv',index_col='Code')
bcancer

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,Malignant
1371026,5,10,10,10,4,10,5,6,3,Malignant
1371920,5,1,1,1,2,1,3,2,1,Benign
8233704,4,1,1,1,1,1,2,1,1,Benign
13454352,1,1,3,1,2,1,2,1,1,Benign

In [42]:
X,y = bcancer.drop('Class', axis = 1) , bcancer['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

# Bagging Classifier

In [43]:
dtc = DecisionTreeClassifier(random_state=26)
lr = LogisticRegression()
knn = KNeighborsClassifier()

bagg = BaggingClassifier(estimator=lr , n_estimators=15 , random_state=26)

bagg.fit(X_train, y_train)
y_pred = bagg.predict(X_test)
accuracy_score(y_test, y_pred)

0.9571428571428572

In [44]:
bagg = BaggingClassifier(estimator=dtc , n_estimators=15 , random_state=26)

bagg.fit(X_train, y_train)
y_pred = bagg.predict(X_test)
accuracy_score(y_test, y_pred)

0.9666666666666667

In [45]:
bagg = BaggingClassifier(estimator=knn , n_estimators=15 , random_state=26)

bagg.fit(X_train, y_train)
y_pred = bagg.predict(X_test)
accuracy_score(y_test, y_pred)

0.9619047619047619

In [46]:
est = [dtc, lr, knn]
n_samples = [10,25,50]
scores = []
for e in est:
    for n in n_samples:
        bagg = BaggingClassifier(estimator=e , n_estimators=n , random_state=26)

        bagg.fit(X_train, y_train)
        y_pred = bagg.predict(X_test)
        scores.append([e, n , accuracy_score(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['Estimator','n','Score'])
df_scores.sort_values(by='Score',ascending=False)

                                 Estimator   n     Score
0  DecisionTreeClassifier(random_state=26)  10  0.966667
1  DecisionTreeClassifier(random_state=26)  25  0.966667
8                   KNeighborsClassifier()  50  0.966667
5                     LogisticRegression()  50  0.961905
2  DecisionTreeClassifier(random_state=26)  50  0.961905
6                   KNeighborsClassifier()  10  0.961905
7                   KNeighborsClassifier()  25  0.961905
4                     LogisticRegression()  25  0.957143
3                     LogisticRegression()  10  0.952381

# Bagging Regresser

In [47]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Concrete_Strength')

In [48]:
concrete_data = pd.read_csv('Concrete_Data.csv')
concrete_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [29]:
X,y = concrete_data.drop('Strength', axis = 1) , concrete_data['Strength']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26)

In [38]:

lr = LinearRegression()
lass = Lasso()
ridg = Ridge()
dtr = DecisionTreeRegressor(random_state=26)

bagg = BaggingRegressor(estimator=lr , n_estimators=15 , random_state=26)

bagg.fit(X_train, y_train)
y_pred = bagg.predict(X_test)
r2_score(y_test, y_pred)

0.6188506436658179

In [39]:
est = [lr,lass, ridg,dtr]
n_samples = [10,25,50]
scores = []
for e in est:
    for n in n_samples:
        bagg = BaggingRegressor(estimator=e , n_estimators=n , random_state=26)

        bagg.fit(X_train, y_train)
        y_pred = bagg.predict(X_test)
        scores.append([e, n , r2_score(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['Estimator','n','Score'])
df_scores.sort_values(by='Score',ascending=False)

                                 Estimator   n     Score
11  DecisionTreeRegressor(random_state=26)  50  0.896730
10  DecisionTreeRegressor(random_state=26)  25  0.893895
9   DecisionTreeRegressor(random_state=26)  10  0.893069
3                                  Lasso()  10  0.620327
6                                  Ridge()  10  0.619630
0                       LinearRegression()  10  0.619629
5                                  Lasso()  50  0.618218
8                                  Ridge()  50  0.617487
2                       LinearRegression()  50  0.617486
4                                  Lasso()  25  0.616078
7                                  Ridge()  25  0.615382
1                       LinearRegression()  25  0.615382