In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier , plot_tree, DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor
from sklearn.ensemble import VotingClassifier

from sklearn.metrics import accuracy_score, r2_score
from sklearn.compose import ColumnTransformer , make_column_selector,make_column_transformer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.pipeline import Pipeline
from tqdm import tqdm

from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
import os 
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Wisconsin')

# Model Ensembling On BreastCancer Dataset
apply DecisionTreeClassifier  , LogisticRegression ,KNeighborsClassifier
calculate indivisual probability for each model    
use hard , soft voting

In [6]:
breast_cancer = pd.read_csv('BreastCancer.csv',index_col='Code')
breast_cancer

          Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  BChromatin  NoemN  Mitoses      Class
Code
61634         5             4              3        1       2      2           2      3        1     Benign
63375         9             1              2        6       4     10           7      7        2  Malignant
76389        10             4              7        2       2      8           6      1        1  Malignant
95719         6            10             10       10       8     10           7     10        7  Malignant
128059        1             1              1        1       2      5           5      1        1     Benign
...         ...           ...            ...      ...     ...    ...         ...    ...      ...        ...
1369821      10            10             10       10       5     10          10     10        7  Malignant
1371026       5            10             10       10       4     10           5      6        3  Malignant
1371920       5             1              1        1       2      1           3      2        1     Benign
8233704       4             1              1        1       1      1           2      1        1     Benign
13454352      1             1              3        1       2      1           2      1        1     Benign

[699 rows x 10 columns]

In [7]:
X,y = breast_cancer.drop('Class', axis = 1) , breast_cancer['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26,stratify=y)

In [8]:
dtc = DecisionTreeClassifier(random_state=26)
lr = LogisticRegression()
knn = KNeighborsClassifier()

voting = VotingClassifier([('TREE', dtc),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)
y_pred = voting.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [22]:
# dtc.fit(X_train,y_train)
# y_pred = dtc.predict_proba(X_test)
# y_pred

# lr.fit(X_train,y_train)
# y_pred = lr.predict_proba(X_test)
# y_pred

array([[9.93486938e-01, 6.51306242e-03],
       [9.97119091e-01, 2.88090856e-03],
       [9.35015921e-01, 6.49840791e-02],
       [9.96276064e-01, 3.72393625e-03],
       [1.25895023e-03, 9.98741050e-01],
       [9.79117831e-02, 9.02088217e-01],
       [9.88960615e-01, 1.10393851e-02],
       [9.98249695e-01, 1.75030499e-03],
       [9.87575922e-01, 1.24240778e-02],
       [9.85998699e-01, 1.40013006e-02],
       [5.74686709e-04, 9.99425313e-01],
       [2.18476626e-03, 9.97815234e-01],
       [9.97886222e-01, 2.11377797e-03],
       [8.42913605e-04, 9.99157086e-01],
       [1.51690927e-02, 9.84830907e-01],
       [9.92142203e-01, 7.85779690e-03],
       [9.98720212e-01, 1.27978811e-03],
       [9.94245070e-01, 5.75492950e-03],
       [6.97093752e-04, 9.99302906e-01],
       [3.62696003e-07, 9.99999637e-01],
       [9.96842377e-01, 3.15762298e-03],
       [9.98720212e-01, 1.27978811e-03],
       [9.91383471e-01, 8.61652875e-03],
       [9.89279228e-01, 1.07207725e-02],
       [1.27333238e-03, 9.98726668e-01],
       [9.97163262e-01, 2.83673784e-03],
       [9.27099796e-01, 7.29002036e-02],
       [9.87077039e-01, 1.29229611e-02],
       [5.25650968e-01, 4.74349032e-01],
       [1.26633344e-02, 9.87336666e-01],
       [9.89279228e-01, 1.07207725e-02],
       [9.98720212e-01, 1.27978811e-03],
       [9.96510651e-01, 3.48934890e-03],
       [2.53055870e-02, 9.74694413e-01],
       [9.87916009e-01, 1.20839905e-02],
       [9.97606606e-01, 2.39339387e-03],
       [9.97109974e-01, 2.89002577e-03],
       [9.72020662e-01, 2.79793384e-02],
       [9.98249695e-01, 1.75030499e-03],
       [8.17655802e-01, 1.82344198e-01],
       [9.96433717e-01, 3.56628337e-03],
       [9.92447045e-01, 7.55295505e-03],
       [9.92142203e-01, 7.85779690e-03],
       [9.92566908e-01, 7.43309186e-03],
       [9.90522474e-01, 9.47752646e-03],
       [4.11898339e-07, 9.99999588e-01],
       [1.02877125e-01, 8.97122875e-01],
       [1.09669730e-02, 9.89033027e-01],
       [9.87077039e-01, 1.29229611e-02],
       [9.84511320e-01, 1.54886802e-02],
       [2.15903620e-02, 9.78409638e-01],
       [9.98117606e-01, 1.88239355e-03],
       [9.94245070e-01, 5.75492950e-03],
       [1.08459732e-03, 9.98915403e-01],
       [5.69203930e-05, 9.99943080e-01],
       [9.98249695e-01, 1.75030499e-03],
       [9.93201370e-01, 6.79862995e-03],
       [4.24822634e-04, 9.99575177e-01],
       [9.96049792e-01, 3.95020849e-03],
       [1.37754220e-05, 9.99986225e-01],
       [6.19207893e-03, 9.93807921e-01],
       [9.97426111e-01, 2.57388866e-03],
       [5.80915545e-02, 9.41908445e-01],
       [9.95231663e-01, 4.76833709e-03],
       [9.93859108e-01, 6.14089221e-03],
       [9.98249695e-01, 1.75030499e-03],
       [9.85029147e-01, 1.49708530e-02],
       [9.98143120e-01, 1.85687979e-03],
       [4.32669389e-03, 9.95673306e-01],
       [9.97606606e-01, 2.39339387e-03],
       [9.99007343e-01, 9.92656577e-04],
       [9.98249695e-01, 1.75030499e-03],
       [3.40976934e-04, 9.99659023e-01],
       [9.98143120e-01, 1.85687979e-03],
       [9.84361704e-01, 1.56382961e-02],
       [9.31868580e-01, 6.81314204e-02],
       [1.79948933e-02, 9.82005107e-01],
       [5.37117143e-03, 9.94628829e-01],
       [9.75874534e-01, 2.41254660e-02],
       [4.54922315e-02, 9.54507768e-01],
       [5.16450224e-03, 9.94835498e-01],
       [2.34253413e-05, 9.99976575e-01],
       [1.75089098e-02, 9.82491090e-01],
       [2.71641686e-02, 9.72835831e-01],
       [9.82955203e-03, 9.90170448e-01],
       [9.98249695e-01, 1.75030499e-03],
       [6.52274281e-03, 9.93477257e-01],
       [9.96646593e-01, 3.35340741e-03],
       [1.85681127e-02, 9.81431887e-01],
       [9.96510651e-01, 3.48934890e-03],
       [9.89279228e-01, 1.07207725e-02],
       [9.69617636e-01, 3.03823644e-02],
       [9.97109974e-01, 2.89002577e-03],
       [9.71239158e-01, 2.87608418e-02],
       [9.90522474e-01, 9.47752646e-03],
       [9.93584646e-01, 6.41535352e-03],
       [9.87575922e-01, 1.24240778e-02],
       [1.64962600e-01, 8.35037400e-01],
       [9.73720717e-01, 2.62792830e-02],
       [9.98720212e-01, 1.27978811e-03],
       [9.82950769e-01, 1.70492311e-02],
       [2.68671237e-03, 9.97313288e-01],
       [9.95404945e-01, 4.59505545e-03],
       [1.07108058e-05, 9.99989289e-01],
       [5.55646498e-02, 9.44435350e-01],
       [6.73463724e-05, 9.99932654e-01],
       [9.93325410e-01, 6.67458987e-03],
       [4.75781827e-01, 5.24218173e-01],
       [9.83134135e-01, 1.68658646e-02],
       [9.98249695e-01, 1.75030499e-03],
       [9.98360159e-01, 1.63984083e-03],
       [9.98642248e-01, 1.35775244e-03],
       [9.96510651e-01, 3.48934890e-03],
       [9.56301455e-03, 9.90436985e-01],
       [9.18053628e-01, 8.19463721e-02],
       [9.98720212e-01, 1.27978811e-03],
       [9.97109974e-01, 2.89002577e-03],
       [9.97606606e-01, 2.39339387e-03],
       [9.86299824e-01, 1.37001757e-02],
       [5.54049680e-02, 9.44595032e-01],
       [9.87884067e-01, 1.21159334e-02],
       [9.94245070e-01, 5.75492950e-03],
       [9.79200120e-01, 2.07998801e-02],
       [9.78085299e-01, 2.19147008e-02],
       [9.98249695e-01, 1.75030499e-03],
       [1.25810387e-03, 9.98741896e-01],
       [9.32061914e-04, 9.99067938e-01],
       [9.98720212e-01, 1.27978811e-03],
       [9.90522474e-01, 9.47752646e-03],
       [9.99007343e-01, 9.92656577e-04],
       [9.98350163e-01, 1.64983689e-03],
       [3.16560586e-03, 9.96834394e-01],
       [2.03809056e-02, 9.79619094e-01],
       [7.11750969e-01, 2.88249031e-01],
       [2.97132561e-02, 9.70286744e-01],
       [9.94942372e-01, 5.05762804e-03],
       [9.97606606e-01, 2.39339387e-03],
       [9.95231663e-01, 4.76833709e-03],
       [3.65474814e-03, 9.96345252e-01],
       [9.95231663e-01, 4.76833709e-03],
       [9.86299824e-01, 1.37001757e-02],
       [9.95231663e-01, 4.76833709e-03],
       [4.71214348e-03, 9.95287857e-01],
       [9.22857561e-01, 7.71424390e-02],
       [1.70582996e-04, 9.99829417e-01],
       [7.77021812e-05, 9.99922298e-01],
       [4.87283861e-01, 5.12716139e-01],
       [5.60031891e-04, 9.99439968e-01],
       [2.34401814e-02, 9.76559819e-01],
       [9.97886222e-01, 2.11377797e-03],
       [9.82401314e-01, 1.75986857e-02],
       [9.66684042e-01, 3.33159584e-02],
       [9.97606606e-01, 2.39339387e-03],
       [9.97222632e-01, 2.77736823e-03],
       [7.46581670e-01, 2.53418330e-01],
       [9.95231663e-01, 4.76833709e-03],
       [3.40650447e-05, 9.99965935e-01],
       [9.98720212e-01, 1.27978811e-03],
       [9.93896148e-01, 6.10385202e-03],
       [9.98720212e-01, 1.27978811e-03],
       [9.95231663e-01, 4.76833709e-03],
       [7.71441058e-04, 9.99228559e-01],
       [1.90451366e-01, 8.09548634e-01],
       [1.89791522e-03, 9.98102085e-01],
       [2.09441552e-01, 7.90558448e-01],
       [9.95405573e-01, 4.59442734e-03],
       [8.65635793e-04, 9.99134364e-01],
       [2.47498662e-03, 9.97525013e-01],
       [4.81547893e-03, 9.95184521e-01],
       [9.96049792e-01, 3.95020849e-03],
       [5.90286003e-03, 9.94097140e-01],
       [8.11099532e-01, 1.88900468e-01],
       [1.21360276e-05, 9.99987864e-01],
       [9.70513811e-01, 2.94861893e-02],
       [1.93721409e-03, 9.98062786e-01],
       [9.90573708e-01, 9.42629228e-03],
       [9.98249695e-01, 1.75030499e-03],
       [9.92876042e-01, 7.12395816e-03],
       [9.10146570e-06, 9.99990899e-01],
       [9.84713123e-01, 1.52868775e-02],
       [9.90522474e-01, 9.47752646e-03],
       [7.69059011e-01, 2.30940989e-01],
       [9.96683118e-01, 3.31688193e-03],
       [9.80389764e-01, 1.96102355e-02],
       [2.55842931e-02, 9.74415707e-01],
       [9.71239158e-01, 2.87608418e-02],
       [9.95231663e-01, 4.76833709e-03],
       [9.66405197e-01, 3.35948030e-02],
       [8.53925459e-04, 9.99146075e-01],
       [9.82401314e-01, 1.75986857e-02],
       [7.73359226e-05, 9.99922664e-01],
       [3.49537434e-04, 9.99650463e-01],
       [9.95231663e-01, 4.76833709e-03],
       [2.98145311e-01, 7.01854689e-01],
       [5.66974727e-04, 9.99433025e-01],
       [9.95231663e-01, 4.76833709e-03],
       [1.15976321e-02, 9.88402368e-01],
       [9.54966449e-01, 4.50335506e-02],
       [9.69211565e-01, 3.07884355e-02],
       [1.31328830e-01, 8.68671170e-01],
       [9.93486938e-01, 6.51306242e-03],
       [9.96510651e-01, 3.48934890e-03],
       [9.97606606e-01, 2.39339387e-03],
       [9.81821391e-01, 1.81786085e-02],
       [9.85998699e-01, 1.40013006e-02],
       [9.94880619e-01, 5.11938144e-03],
       [9.92684922e-01, 7.31507842e-03],
       [2.57648478e-02, 9.74235152e-01],
       [9.37937651e-01, 6.20623489e-02],
       [9.91840672e-01, 8.15932768e-03]])

In [23]:
voting.named_estimators_

{'TREE': DecisionTreeClassifier(random_state=26),
 'LR': LogisticRegression(),
 'KNN': KNeighborsClassifier()}

# Find best parameters   

default voting = 'hard'

In [29]:
depths = [None, 2,3,4,5,6,7]
solvers = ['lbfgs','saga','sag','liblinear']
ks = [2,5,10]
scores = []

for d in depths:
    for s in solvers:
        for k in ks:
            dtc = DecisionTreeClassifier(random_state=26, max_depth=d)
            lr = LogisticRegression(solver=s)
            knn = KNeighborsClassifier(n_neighbors=k)

            voting = VotingClassifier([('TREE', dtc),('LR',lr),('KNN',knn)])
            voting.fit(X_train,y_train)
            y_pred = voting.predict(X_test)

            scores.append([d,s,k,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores, columns=['Depth','Solver','K','Score'])
df_scores.sort_values(by='Score',ascending=False)

    Depth Solver   K     Score
2     NaN  lbfgs  10  0.966667
14    2.0  lbfgs  10  0.966667
38    4.0  lbfgs  10  0.966667
26    3.0  lbfgs  10  0.966667
62    6.0  lbfgs  10  0.966667
..    ...    ...  ..       ...
31    3.0    sag   5  0.952381
43    4.0    sag   5  0.952381
55    5.0    sag   5  0.952381
67    6.0    sag   5  0.952381
79    7.0    sag   5  0.952381

[84 rows x 4 columns]

voting = 'hard'

In [30]:
depths = [None, 2,3,4,5,6,7]
solvers = ['lbfgs','saga','sag','liblinear']
ks = [2,5,10]
scores = []

for d in depths:
    for s in solvers:
        for k in ks:
            dtc = DecisionTreeClassifier(random_state=26, max_depth=d)
            lr = LogisticRegression(solver=s)
            knn = KNeighborsClassifier(n_neighbors=k)

            voting = VotingClassifier([('TREE', dtc),('LR',lr),('KNN',knn)], voting='soft')   # soft use .predict_proba for each model then takes avg
            voting.fit(X_train,y_train)
            y_pred = voting.predict(X_test)

            scores.append([d,s,k,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores, columns=['Depth','Solver','K','Score'])
df_scores.sort_values(by='Score',ascending=False)

    Depth     Solver  K     Score
30    3.0        sag  2  0.971429
33    3.0  liblinear  2  0.971429
24    3.0      lbfgs  2  0.971429
27    3.0       saga  2  0.971429
36    4.0      lbfgs  2  0.971429
..    ...        ... ..       ...
70    6.0  liblinear  5  0.957143
82    7.0  liblinear  5  0.957143
76    7.0       saga  5  0.957143
61    6.0      lbfgs  5  0.952381
73    7.0      lbfgs  5  0.952381

[84 rows x 4 columns]

# Evaluating the indivisual estimators

add weights based on indivisual accuracy to each model

In [39]:


y_test_enc = np.where(y_test=='Malignant' ,1 ,0)

y_pred = voting.named_estimators_['TREE'].predict(X_test)
print('Tree acc = ',accuracy_score(y_test_enc, y_pred))

y_pred = voting.named_estimators_['LR'].predict(X_test)
print('LR acc = ',accuracy_score(y_test_enc, y_pred))

y_pred = voting.named_estimators_['KNN'].predict(X_test)
print('KNN acc = ',accuracy_score(y_test_enc, y_pred))

Tree acc =  0.9476190476190476
LR acc =  0.9619047619047619
KNN acc =  0.9666666666666667

In [40]:
depths = [None, 2,3,4,5,6,7]
solvers = ['lbfgs','saga','sag','liblinear']
ks = [2,5,10]
scores = []

for d in depths:
    for s in solvers:
        for k in ks:
            dtc = DecisionTreeClassifier(random_state=26, max_depth=d)
            lr = LogisticRegression(solver=s)
            knn = KNeighborsClassifier(n_neighbors=k)

            voting = VotingClassifier([('TREE', dtc),('LR',lr),('KNN',knn)], voting='soft', weights=[0.3,1,1])   # soft use .predict_proba for each model then takes avg
            voting.fit(X_train,y_train)
            y_pred = voting.predict(X_test)

            scores.append([d,s,k,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores, columns=['Depth','Solver','K','Score'])
df_scores.sort_values(by='Score',ascending=False)

    Depth     Solver  K     Score
3     NaN       saga  2  0.966667
18    2.0        sag  2  0.966667
9     NaN  liblinear  2  0.966667
6     NaN        sag  2  0.966667
15    2.0       saga  2  0.966667
..    ...        ... ..       ...
34    3.0  liblinear  5  0.957143
58    5.0  liblinear  5  0.957143
67    6.0        sag  5  0.957143
52    5.0       saga  5  0.957143
55    5.0        sag  5  0.952381

[84 rows x 4 columns]

In [42]:
# On Concrete _Strength Dataset