In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import lasso_regression, lasso
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error ,mean_squared_error,r2_score   # use tab to get auto suggestion 
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [25]:
df = pd.read_csv('Housing.csv')
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [26]:
x = df.drop('price', axis=1)
y = df['price']

encoder = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')

In [27]:
num_cols = list(x.columns[x.dtypes == int])

In [28]:
str_cols = list(x.columns[x.dtypes != int])

In [29]:
x_num = x[num_cols]
x_str = x[str_cols]

x_ohe = encoder.fit_transform(x_str)
x_enc = pd.concat([x_ohe,x_num], axis = 1)

In [30]:
x_enc

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,6000,3,1,2,1

In [31]:
x_train , x_test, y_train, y_test = train_test_split(x_enc, y , test_size = 0.3, random_state = 26)

In [35]:
lasso = Lasso)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)

root_mean_squared_error(y_test, y_pred)

15070.47480878495

In [36]:
lasso.coef_

array([6.28094679e+03, 3.21975767e+03, 6.71200452e+03, 1.04578147e+04,
       1.23047338e+04, 9.41029097e+03, 4.56610469e+00, 2.06191429e+03,
       1.33910373e+04, 6.02801491e+03, 3.34603053e+03])

In [ ]:
# ========================================================

In [39]:
lasso = Lasso(alpha=0.5)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([6.36187958e+03, 3.21338971e+03, 6.71962636e+03, 1.08160358e+04,
       1.23942853e+04, 9.47811195e+03, 4.55716109e+00, 2.05292590e+03,
       1.34612465e+04, 6.01158400e+03, 3.33253522e+03])

In [40]:
lasso.intercept_

np.float64(-7039.363023011698)

In [38]:
lasso = Lassoalpha=0.5)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([6.36187958e+03, 3.21338971e+03, 6.71962636e+03, 1.08160358e+04,
       1.23942853e+04, 9.47811195e+03, 4.55716109e+00, 2.05292590e+03,
       1.34612465e+04, 6.01158400e+03, 3.33253522e+03])

In [ ]:
# ========================================================

In [51]:
alphas = [0.1,0.25,0.7,1,1.5,2,5,10,50]
scores =[]
for a in alphas:
    lasso = Lassoalpha=a)
    lasso.fit(x_train, y_train)
    y_pred = lasso.predict(x_test)
    scores.append([a, root_mean_squared_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score')

   alpha         score
0   0.10  15054.589007
1   0.25  15057.144271
2   0.70  15065.039848
3   1.00  15070.474809
4   1.50  15079.794114
5   2.00  15089.392353
6   5.00  15150.756031
7  10.00  15259.102602
8  50.00  16100.225468