In [117]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error ,mean_squared_error,r2_score   # use tab to get auto suggestion 
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [118]:
df = pd.read_csv('Housing.csv')
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [119]:
 df.dtypes

price       float64
lotsize       int64
bedrooms      int64
bathrms       int64
stories       int64
driveway        str
recroom         str
fullbase        str
gashw           str
airco           str
garagepl      int64
prefarea        str
dtype: object

In [120]:
x = df.drop('price', axis=1)
y = df['price']

encoder = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')

In [121]:
num_cols = list(x.columns[x.dtypes == int])

In [122]:
str_cols = list(x.columns[x.dtypes != int])

In [123]:
x_num = x[num_cols]
x_str = x[str_cols]

x_ohe = encoder.fit_transform(x_str)
x_enc = pd.concat([x_ohe,x_num], axis = 1)

In [124]:
x_enc

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,6000,3,1,2,1

In [125]:
x_train , x_test, y_train, y_test = train_test_split(x_enc, y , test_size = 0.3, random_state = 26)

In [126]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [127]:
res = lr.predict(x_test)

In [128]:
root_mean_squared_error(y_test, res)

15052.908713866158

In [129]:
r2_score(y_test, res)

0.6791781818067955

In [130]:
# ==================================

In [142]:

poly = PolynomialFeatures(degree = 2,include_bias = False).set_output(transform = 'pandas')
x_poly =poly.fit_transform(x_enc)
x_train , X_test, y_train, y_test = train_test_split(x_poly, y, random_state = 26, test_size = 0.3)

lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(X_test)


root_mean_squared_error(y_test, y_pred)

15193.26507443132

In [143]:

poly = PolynomialFeatures(degree = 1,include_bias = False).set_output(transform = 'pandas')
x_poly =poly.fit_transform(x_enc)
x_train , X_test, y_train, y_test = train_test_split(x_poly, y, random_state = 26, test_size = 0.3)

lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(X_test)


root_mean_squared_error(y_test, y_pred)

15052.908713866158